language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t willvac/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true willvac/docker-react npm run test
